NETWORK_PASSPHRASE="Public Global Stellar Network ; February 2022"
FEDERATION_SERVER="https://api.github.com/Danejw/federation"
AUTH_SERVER="https://api.github.com/Danejw/auth"
TRANSFER_SERVER="https://api.github.com/Danejw"
SIGNING_KEY="GAXDULLORURF3W4P5LYH2EWCXMCNOLN6GEERN67SBZY52CEKZ2JSWIPC"
HORIZON_URL="https://horizon.github.com/Danejw"
ACCOUNTS=[
"GAXDULLORURF3W4P5LYH2EWCXMCNOLN6GEERN67SBZY52CEKZ2JSWIPC"
"GAGZFNI5RRJXTOW6FZ3VRJVUEYJVSHSFVQMGOLSQ3LFQH6MXW3BNTSSK"
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="Sand Slide Krew"
ORG_DBA="SSK"
ORG_URL="https://github.com/Danejw.com"
ORG_LOGO="?"
ORG_DESCRIPTION="Made in Hawaii, By da Boys, For da Boys"
ORG_PHYSICAL_ADDRESS="Westside, Shores, HI 96707, United States"
ORG_OFFICIAL_EMAIL="theesupremekai@gmail.com"

[[PRINCIPALS]]
name="Dickie"
email="theesupremekai@gmail.com"
github="SupremeKai69"

# asset with meta info
[[CURRENCIES]]
code="SSK"
issuer="GAXDULLORURF3W4P5LYH2EWCXMCNOLN6GEERN67SBZY52CEKZ2JSWIPC"
display_decimals=3
name="SSK Tokens"
conditions="There will only ever be 1,000,000 SSK tokens in existence. We will distribute the revenue during special events only"
image="?"
